### ISSUE TITLE
Upload errors for large image collections

### ISSUE THREAD

**Issue by MyleneSimon** [usnistgov/WIPP#30]
**Select category**

(check which category applies to the bug you are reporting)
- [ ] Installation
- [ ] WIPP (general)
- [x] WIPP (data)
- [ ] WIPP (plugins)
- [ ] WIPP (workflows)
- [ ] Argo Workflows
- [ ] Jupyter Notebooks
- [ ] Plots
- [ ] Other

**Summary**

Uploading a large image collection can result in upload errors for some of the images, if the upload takes more than 5 min.

**What is the current *bug* behavior?**

After a few minutes, some of the uploads are stopped with the error "Unknown upload error.". It appears that the auth token sent with some of the chunks was expired when it reached the backend.

**What is the expected *correct* behavior?**

All of the chunks/images are uploaded without errors.

**Steps to reproduce**

Select a large collection of images to upload (ie thousands of images), after about 5min, some of the uploads will start failing.

**Relevant screenshots and/or logs**

Backend was returning `401 - Unauthorized` errors.

**Environment info**

Only happening with versions 3.0.x (not the alpha or beta ones), since the introduction of access control and user management.

**Possible fixes**

Change the way the token is attached to the headers of the chunk POST requests so that the latest one is sent with each request.

**Comment by tomgreen66** [comment]
Hi - think we have hit this issue locally.  I see the following error in the backend logs:
```
$ kubectl logs wipp-backend-aaaaaa-aa
...
2021-05-06 22:05:35.137 ERROR 7 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in cont
ext with path [] threw exception

java.io.FileNotFoundException: /data/WIPP-plugins/temp/collections/609467ed70754b5bbfe37855/metadata_files/img-global-positions-1.txt (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_212]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_212]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_212]
        at gov.nist.itl.ssd.wipp.backend.data.utils.flowjs.FlowjsController.uploadChunck(FlowjsController.java:92) ~[wipp-backend-data-3.0.1.jar!/:na]
        at gov.nist.itl.ssd.wipp.backend.data.imagescollection.files.FileUploadController.uploadChunck(FileUploadController.java:80) ~[wipp-backend-data-3
.0.1.jar!/:na]
...
```

**Comment by tomgreen66** [comment]
Actually - maybe not related.  Will open another bug report.
