### ISSUE TITLE
Cannot upload files into collection

### ISSUE THREAD

**Issue by tomgreen66** [usnistgov/WIPP#32]
**Select category**

(check which category applies to the bug you are reporting)
- [ ] Installation
- [x] WIPP (general)
- [ ] WIPP (data)
- [ ] WIPP (plugins)
- [ ] WIPP (workflows)
- [ ] Argo Workflows
- [ ] Jupyter Notebooks
- [ ] Plots
- [ ] Other

**Summary**

When I try to upload a file into a new collection I get a "Unknown upload error" and the file doesnt upload.

**What is the current *bug* behavior?**

The current bug behaviour is the file does not upload and I cant see any trace in the logs of possible issues.

**What is the expected *correct* behavior?**

For file to be uploaded.

**Steps to reproduce**

This may be related to using a Kubernetes Cluster rather than a standalone.  I found #5 could be required since I noticed I had following lots of the following errors:
```
$ kubectl logs vision-api-aaaaaaaaa-aa
...
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
...
```

**Relevant screenshots and/or logs**

```
$ kubectl logs vision-api-aaaaaaa-aaaa
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
```
```
$ kubectl logs wipp-frontend-aaaaaaaa-aaaa
10.0.0.129 - - [07/May/2021:12:22:55 +0000] "GET /api/imagesCollections/60946b6670754b5bbfe3785f/images?flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=213250&flowTotalSize=213250&flowIdentifier=213250-img_r001_c002tif&flowFilename=img_r001_c002.tif&flowRelativePath=img_r001_c002.tif&flowTotalChunks=1 HTTP/1.1" 401 0 "http://131.251.132.195:32001/images-collection/60946b6670754b5bbfe3785f" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
2021/05/07 12:22:55 [warn] 10#10: *637 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000222, client: 10.0.0.129, server: distrib, request: "POST /api/imagesCollections/60946b6670754b5bbfe3785f/images?flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=213250&flowTotalSize=213250&flowIdentifier=213250-img_r001_c002tif&flowFilename=img_r001_c002.tif&flowRelativePath=img_r001_c002.tif&flowTotalChunks=1 HTTP/1.1", host: "131.251.132.195:32001", referrer: "http://131.251.132.195:32001/images-collection/60946b6670754b5bbfe3785f"
10.0.0.129 - - [07/May/2021:12:22:55 +0000] "POST /api/imagesCollections/60946b6670754b5bbfe3785f/images?flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=213250&flowTotalSize=213250&flowIdentifier=213250-img_r001_c002tif&flowFilename=img_r001_c002.tif&flowRelativePath=img_r001_c002.tif&flowTotalChunks=1 HTTP/1.1" 401 0 "http://131.251.132.195:32001/images-collection/60946b6670754b5bbfe3785f" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
```

**Environment info**

Latest version on Github as on 7th May 2021.

**Possible fixes**

Possibly #5 is related but unsure if connected to upload mechanism.

**Comment by tomgreen66** [comment]
Also the following:
```
$ kubectl logs wipp-backend-aaaaaaa-aaaa
...
2021-05-07 12:43:34.206 ERROR 7 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.io.FileNotFoundException: /data/WIPP-plugins/temp/collections/609535bf70754b5bbfe37860/images/img_r001_c004.tif (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_212]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_212]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_212]
	at gov.nist.itl.ssd.wipp.backend.data.utils.flowjs.FlowjsController.uploadChunck(FlowjsController.java:92) ~[wipp-backend-data-3.0.1.jar!/:na]
	at gov.nist.itl.ssd.wipp.backend.data.imagescollection.files.FileUploadController.uploadChunck(FileUploadController.java:80) ~[wipp-backend-data-3.0.1.jar!/:na]
```

**Comment by MyleneSimon** [comment]
Hi @tomgreen66, the APM server connection errors you see in the `vision-api` logs should not be an issue here, it just means that the monitoring server is not found and that should not affect the image upload.
In the `wipp-backend` logs that you posted, there is a `Permission denied` error here:
`java.io.FileNotFoundException: /data/WIPP-plugins/temp/collections/609535bf70754b5bbfe37860/images/img_r001_c004.tif (Permission denied)`
So I am thinking there could be a permission issue with the data volume? 

A few questions that may help us narrow down the issue:
- what kind of PV are you using for this deployment? 
- which container runtime is used in this cluster?
- is there a `securityContext` set for the backend?

**Comment by tomgreen66** [comment]
Thank you for your advice. It triggered a memory that I need to use `securityContext` for the container to use our CephFS share - it seems to work when a level is applied to the backed container e.g.
```
       containers:
         - image: wipp/wipp-backend:3.0.1
           name: wipp-backend
           securityContext:
             seLinuxOptions:
               level: ...
```

Would there be any other places where this may be required? I will have to go through an example and see how far I get.

Thanks again.
